#!/usr/bin/sh

# Run this and then  make sure you export TNS_ADMIN=/tmp before
# running the service that needs it.

cat <<EOF > /tmp/tnsnames.ora
ORA_CLUSTER.WORLD =
 (DESCRIPTION =
   (ADDRESS_LIST =
     (ADDRESS = (PROTOCOL = TCP)(HOST = gvicjbaora01)(PORT = 1521))
     (ADDRESS = (PROTOCOL = TCP)(HOST = gvicjbaora02)(PORT = 1521))
     (LOAD_BALANCE = YES)
   )
 (CONNECT_DATA =
   (SERVICE_NAME = gvorac)
 )
)
EOF

cat <<EOF > /tmp/sqlnet.ora
NAMES.DIRECTORY_PATH= (TNSNAMES, ONAMES, HOSTNAME)
EOF
