#!/bin/bash

export PATH=$PATH:$HOME/code/admin-cli
export GALILEO_PORT="11131"
export GALILEO_LOG_FRIENDLY=1
#export GALILEO_URI="http://localhost:${GALILEO_PORT}"
export GALILEO_URI="http://karl.galileosuite.com:${GALILEO_PORT}"
alias mygpeadmin='GALILEO_USERNAME=rdavis GALILEO_PASSWORD=Passw0rd1@ GALILEO_URI="${GALILEO_URI}" GALILEO_SITE=rdavis gpeadmin.rb'
alias mygpefakefile='echo "gem.$(date +"%Y%m%d").$(date +"%H%M%S").$(date +"%Z").d60b21da185e11e682260894ef035c20.tsm.gz"'
alias mygperedordavis='mygpeadmin unlock_site && mygpeadmin remove_site && mygpeadmin add_site paid'
alias gpe='cd ~/code/gpe-server'
alias mygpepassenger='cd ~/code/gpe-server && GALILEO_LOG_FRIENDLY=1 bundle exec passenger start --min-instances=3 --port="${GALILEO_PORT}" ui'
alias mygpeuibuid='cd ~/code/gpe-server/ui/app && yarn clean && yarn install && yarn release'
alias ts='BUNDLE_GEMFILE=~/code/gpe-server/Gemfile OUTPUT=$HOME/p2files GALILEO_LOG_FRIENDLY=1 CUSTOMER=rdavis bundle exec test-single-file'

export PATH=$PATH:$HOME/code/galileo-tools

# Add my scripts to PATH
export PATH=$HOME/code/scripts:$PATH

export OUTPUT=$HOME/p2files
mygperunetlbyname () {
  for i in $(ls ~/gpe/*/*.tsm.gz | cut -d. -f1 | uniq); do
    d=~/gpe/etl/$(echo $i | cut -d/ -f5)/$(echo $i | cut -d/ -f6).log
    mkdir -p "$(dirname $d)"
    echo "set +o noclobber; ts --no-batch $i.*.tsm.gz > $d 2>&1 &"
  done
}

mygpeexpand () {
  match=${1:-summary_extended}
  for i in *.tsm.gz; do
    echo $i
    eval "tar -xOf $i '${match}*'"
  done
}


mygpetsmlastrun () {
  c=${1:-1}
  for i in $(mygpetsmlast $c); do
    eval "ts $i &"
  done
}

mygpetsmfirstrun () {
  c=${1:-1}
  for i in $(mygpetsmlast $c); do
    eval "ts $i &"
  done
}


mygpetsmlast () {
  c=${1:-1}
  for i in $(ls -d ~/gpe/*); do
    for i in $(ls $i/*.tsm.gz | cut -d. -f1 | uniq); do
      ls $i.*.tsm.gz | tail -"${c}"
    done
  done
}

mygpetsmfirst () {
  c=${1:-1}
  for i in $(ls -d ~/gpe/*); do
    for i in $(ls $i/*.tsm.gz | cut -d. -f1 | uniq); do
      ls $i.*.tsm.gz | head -"${c}"
    done
  done
}

mygpecleardirs () {
  rm -rf ~/gpe ~/p2files && mkdir ~/gpe ~/p2files/
}

ffile () {
  find ~/gpe -type f -name '*.gz' | sort  | grep -E "$1" | grep -v 'gpe.gz'
}

myetl () {
  if [ "$1" = '-x' ] ; then
    shift
    for i in $(ffile "$1");do eval "ts $i &"; done
  else
    for i in $(ffile "$1");do echo "ts $i &"; done
  fi
}

dirlist () {
  for i in *.gz
  do
    eval "tar -xOf $i '$1*'"
  done
}

function mygpefiledelete () {
  find ~/p2files/ -name '*.tsm.gpe.gz' -type f -exec rm {} \;
}

function mygpecreateviews () {
  BUNDLE_GEMFILE=$HOME/code/gpe-server/Gemfile
  bundle exec create-views  --site rdavis --execute
}

function mygpeedithelpers () {
  vi ~/code/my-bash-helpers
}

mygpeyarn () {
  cd ~/code/gpe-server/ui/app
  yarn clean && yarn install && yarn release
  cd ~/code/gpe-server/
  ./setup.sh testing
}

mygpes3mkpath () {
  prefix="s3://etl-x2gpe.galileosuite.com"
  echo "${prefix}/$1"
}

mygpes3get () {
  year=$(date +"%Y")
  month=$(date +"%m")
  day=$(date +"%d")
  if [ "$1" = '-ls' ]; then
    echo "aws s3 ls --recursive s3://etl-x2gpe.galileosuite.com/Analysis_Group/cc83aceacf83e6119c673cfdfe02e7c2/${year}/${month}/${day}/"
    echo "aws s3 ls --recursive s3://etl-x2gpe.galileosuite.com/DandH/5ab25322eb0ce811a58e7cd30aea05f0/${year}/${month}/${day}/"
    echo "aws s3 ls --recursive s3://etl-x2gpe.galileosuite.com/VWR/a64fbe739e9de511a5f80025b50a006d/${year}/${month}/${day}/"
    echo "aws s3 ls --recursive s3://etl-x2gpe.galileosuite.com/VWR/b64c1f141101e811959b0025b5a4005d/${year}/${month}/${day}/"
    echo "aws s3 ls --recursive s3://etl-x2gpe.galileosuite.com/VWR/60e527c0992de611bc580025b50401ff/${year}/${month}/${day}/"
    echo "aws s3 ls --recursive s3://etl-x2gpe.galileosuite.com/atsgroup/d60b21da185e11e682260894ef035c20/${year}/${month}/${day}/"
    echo "aws s3 ls --recursive s3://etl-x2gpe.galileosuite.com/Dept_REV/f2d2bef01af811df8bd9009a01040000/${year}/${month}/${day}/"
    echo "aws s3 ls --recursive s3://etl-x2gpe.galileosuite.com/Dept_LI/a46df78a0f3eea11acb33868dd1ca649/${year}/${month}/${day}/"
  else
    echo "aws s3 cp --recursive s3://etl-x2gpe.galileosuite.com/Analysis_Group/cc83aceacf83e6119c673cfdfe02e7c2/${year}/${month}/${day}/  ~/gpe/ag/"
    echo "aws s3 cp --recursive s3://etl-x2gpe.galileosuite.com/DandH/5ab25322eb0ce811a58e7cd30aea05f0/${year}/${month}/${day}/ ~/gpe/DandH/"
    echo "aws s3 cp --recursive s3://etl-x2gpe.galileosuite.com/VWR/a64fbe739e9de511a5f80025b50a006d/${year}/${month}/${day}/ ~/gpe/vwr/"
    echo "aws s3 cp --recursive s3://etl-x2gpe.galileosuite.com/VWR/b64c1f141101e811959b0025b5a4005d/${year}/${month}/${day}/ ~/gpe/vwr/"
    echo "aws s3 cp --recursive s3://etl-x2gpe.galileosuite.com/VWR/60e527c0992de611bc580025b50401ff/${year}/${month}/${day}/ ~/gpe/vwr/"
    echo "aws s3 cp --recursive s3://etl-x2gpe.galileosuite.com/atsgroup/d60b21da185e11e682260894ef035c20/${year}/${month}/${day}/ ~/gpe/atsgroup/"
    echo "aws s3 cp --recursive s3://etl-x2gpe.galileosuite.com/Dept_REV/f2d2bef01af811df8bd9009a01040000/${year}/${month}/${day}/ ~/gpe/rev/"
    echo "aws s3 cp --recursive s3://etl-x2gpe.galileosuite.com/Dept_LI/a46df78a0f3eea11acb33868dd1ca649/${year}/${month}/${day}/ ~/gpe/li/"
  fi
}

mygperestartwatch () {
  kubectl rollout restart deployment ch-ui-blue ch-etl-x2gpe
  kubectl rollout status -w  deployment ch-etl-x2gpe
  kubectl rollout status -w  deployment ch-ui-blue
}
