#!/bin/bash

num=4
c=0
cd ~/code/gpe-server
for i in $*
do
  echo "Run test-single-file: '$i'"
  c=$((c+1))
  moveto="$(dirname $i)/old"
  mkdir -p "${moveto}"
  eval "(bundle exec bin/test-single-file --summary 1 --customer '${GALILEO_SITE}' '$i' && mv '$i' '$moveto') &"
  if [ $c -eq "$num" ]; then
    wait
    c=0
  fi
done
