#!/bin/bash

num=5
c=0
cd ~/code/gpe-server
for i in $*
do
  echo "TEST_SINGLE_FILE: '$i'"
  c=$((c+1))
  eval "bundle exec bin/test-single-file --customer ${GALILEO_SITE} $i &"
  if [ $c -eq "$num" ]; then
    wait
    c=0
  fi
done
