#!/bin/sh

echo "Stoping yard server if already running..."
echo "Stop status" $?

echo "Rebuilding Documentation..."
cd /home/ATS/rdavis/src/gpe-server/sources
yard doc --private galileo*/**/*.rb

echo "Starting yard server with --reload..."
yard server --bind gpedevdb01.ats.local --reload > /dev/null 2>&1 &

echo "Browse to http://gpedevdb01.ats.local:8808 for documentation."
