#!/bin/sh

         shorthost=$(hostname -s)
             nanos=$(gdate +"%s%N")

          customer="${1}"  ;shift

              item="${1}"  ;shift
         othertags="${1}"  ;shift
            fields="${1}"  ;shift

            #  url="xfer1.galileosuite.com:443"          # Production
               url="xfer1-dev.galileosuite.com:1447"     # Development

           payload="payload.$item.$RANDOM.influx"

# Are there credentials already? If so warn and exit
if [ -f .credentials ]; then
  apiuser="$(cat .credentials | head -1)"
else
  echo ".credentials file was not found."
  exit 1
fi

echo "${item},${othertags} ${fields} ${nanos}" > "${payload}"

cmd="curl -vkX POST -H 'Content-Type: text/plain' \
  --data-binary @'${payload}' \
  -u '${apiuser}' \
  'https://${url}/ingest/influx/${customer}/write?db=${shorthost}'"

if [ "$*" = "-x" ] ; then
  eval "${cmd}" > execute.log 2>&1
else
  echo "${cmd}"
  cat "${payload}"
  echo "Nothing done: Include the -x flag at the end to execute."
fi

rm -if "${payload}"






