#!/bin/sh

# Write to LIVE_atsgroup
# Item will be hostname.system (makepayload adds the hostname to the system item added
# Type and Name reserve words for the DB type and the CfgName
# The remaining is trend if numeric or Config if other

./makepayload LIVE_atsgroup \
  "$(hostname).disk1,type=host,name=$(hostname -s),host=$(hostname)" \
  " cpu=10,mem=100,custom=\"Rich Davis Data2\"" $*
